version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  #observation: the root username and password cannot be the same as the mysql username and password
  mysql:
    image: mysql:latest
    restart: always
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
  
volumes:
  data:
  
