admin:
  email: admin@super.ctf
  name: admin
  password: Ri5eSFm_r2WEntozP8T7Yw
appearance:
  description: My CTF description
  name: EYF CTF
mode: teams
time:
  end: '1753780800'
  start: '1752493200'
